name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Install Checkout 
        uses: actions/checkout@v2
      - name: Install Setup-Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Instal bats 
        run: npm install -g bats
      - name: Check bats version
        run: bats -v
